### ISSUE TITLE
Update or remove Carthage/Checkouts

### ISSUE THREAD

**Issue by wtmoose** [ReactKit/SwiftTask#32]
When compiling my project's main target, Xcode sometimes compiles the SwiftTask's Carthage/Checkouts directory, which includes outdated libraries. In my case, this breaks my build because the version of Alamofire doesn't compile under Swift 1.2. The only fix I've found is to delete these checkouts sources locally.

This may be a problem in my project configuration, but it seems like these sources should be kept up-to-date or removed.

**Comment by inamiy** [comment]
Which SwiftTask version are you using?
For Swift 1.2 support, please check current ver `3.1.0` where Alamofire is updated in 30014bf3b0.

Also, I recommend you to check your project or build configuration
because SwiftTask uses Alamofire just for test cases only 
and dependency is marked as private (both in Carthage and CocoaPods),
so Alamofire should not be compiled at anytime even if it is older (non-Swift 1.2 support) version.

**Comment by wtmoose** [comment]
I'm on 3.1.0. I think somewhere in the SwiftTask source tree is an Alamofire file that doesn't support Swift 1.2. Most recently, the problem happened immediately after an Xcode crash, so I suppose the crash had left my project in a bad state. Next time it happens I'll take a closer look. Thanks for the reply.

**Comment by wtmoose** [comment]
Closing this because I suspect my problems were caused by this issue Carthage/Carthage/issues/479 with Carthage fetching multiple versions of a dependency.

I went ahead and filed the issue against Carthage because it looks like your Carthage config is correct.
